language: java
jdk:
  - openjdk10

# os: linux
# dist: trusty

os: osx

# cache:
#   directories:
#     - boehmgc

matrix:
  include:
    -env: 

    # Clang 5.0
    - env: CLANG_VERSION=5.0 BOEHM_VERSION=7.6.4
      addons: &clang50
        apt:
          packages:
            - clang-5.0
            - libatomic-ops-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

install: 
  # Install Boehm GC
  - curl http://www.hboehm.info/gc/gc_source/gc-${BOEHM_VERSION}.tar.gz | tar -xz
  - cd gc-${BOEHM_VERSION}
  - ./configure && make && make install

before_script:
  - git lfs pull

script:
  - make
  - make tests
