language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - /usr/local/Homebrew

env: BOEHM_VERSION=7.6.4

addons:
  homebrew:
    packages:
    - llvm@5
    - git-lfs
    - ant@1.9
    - libatomic_ops
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-5.0 llvm-5.0 llvm-5.0-dev libllvm5.0 libstdc++6 libstdc++-4.8-dev libgcc-4.8-dev libobjc-4.8-dev libclang-common-5.0-dev libclang1-5.0 llvm-5.0-runtime libllvm5.0 libstdc++6 libllvm5.0
  # apt:
  #   sources:
  #   - sourceline: deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main
  #     key_url: http://llvm.org/apt/llvm-snapshot.gpg.key
  #   packages:
  #   - clang-5 llvm-5 llvm-5-dev
  #   # - ant=1.9
  #   # - libatomic_ops



matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.3

    - os: linux
      dist: precise

install: 
  - /usr/libexec/java_home -V

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo LINUX
    else
      # Install llvm 5
      # brew install --force-bottle llvm@5
      export PATH="/usr/local/opt/llvm@5/bin:$PATH"

      # Install git-lfs
      # brew install git-lfs

      # Install ant 1.9 
      # brew install ant@1.9
      export PATH="/usr/local/opt/ant@1.9/bin:$PATH"

      # Install libatomic_ops
      # brew install libatomic_ops || brew upgrade libatomic_ops     
    fi
  
  # Install Boehm GC
  - curl -OL http://www.hboehm.info/gc/gc_source/gc-${BOEHM_VERSION}.tar.gz
  - sudo tar -xzf gc-${BOEHM_VERSION}.tar.gz
  - cd gc-${BOEHM_VERSION}
  - sudo ./configure 
  - sudo make 
  - sudo make install

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - git lfs pull
  - /usr/libexec/java_home -V

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
      export JDK7=$(/usr/libexec/java_home -v 1.7)
    else
      export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
      export JDK7=$(/usr/libexec/java_home -v 1.8)
    fi

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      make
      make tests
    else
      make
    fi