language: java

# os: linux
# dist: trusty

os: osx

# Clang 5.0
compiler: clang
osx_image: xcode9.4

cache:
  directories:
    - /usr/local/Homebrew

matrix:
  include:
    - env: BOEHM_VERSION=7.6.4
      # addons: &clang50
      #   apt:
      #     packages:
      #       - clang-5.0
      #       - libatomic-ops-dev
      #     sources:
      #       - ubuntu-toolchain-r-test
      #       - llvm-toolchain-trusty-5.0
      #       - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
      #         key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

install: 
  #Install azul JDK 7
  - brew cask install caskroom/versions/zulu7
  - export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-7.jdk/Contents/Home

  # Install llvm 5
  - brew install --force-bottle llvm@5
  - export PATH="/usr/local/opt/llvm@5/bin:$PATH"

  # Install git-lfs
  - brew install git-lfs

  # Install ant 1.9 
  - brew install ant@1.9
  - export PATH="/usr/local/opt/ant@1.9/bin:$PATH"

  # Install libatomic_ops
  - brew install libatomic_ops || brew upgrade libatomic_ops 
  
  # Install Boehm GC
  - curl -OL http://www.hboehm.info/gc/gc_source/gc-${BOEHM_VERSION}.tar.gz
  - sudo tar -xzf gc-${BOEHM_VERSION}.tar.gz
  - cd gc-${BOEHM_VERSION}
  - sudo ./configure 
  - sudo make 
  - sudo make install

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - git lfs pull
  - export JDK7=${JAVA_HOME}

script:
  - sudo make
  - sudo make tests
